#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kaede3rd
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="huruhon")]
	public partial class DBClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void Insertoperator(@operator instance);
    partial void Updateoperator(@operator instance);
    partial void Deleteoperator(@operator instance);
    partial void Insertreceipt(receipt instance);
    partial void Updatereceipt(receipt instance);
    partial void Deletereceipt(receipt instance);
    partial void Insertconfig(config instance);
    partial void Updateconfig(config instance);
    partial void Deleteconfig(config instance);
    partial void Insertgenre(genre instance);
    partial void Updategenre(genre instance);
    partial void Deletegenre(genre instance);
    partial void Insertitem(item instance);
    partial void Updateitem(item instance);
    partial void Deleteitem(item instance);
    partial void Insertbox(box instance);
    partial void Updatebox(box instance);
    partial void Deletebox(box instance);
    #endregion
		
		public DBClassDataContext() : 
				base(global::huruhon.Properties.Settings.Default.huruhonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<@operator> @operator
		{
			get
			{
				return this.GetTable<@operator>();
			}
		}
		
		public System.Data.Linq.Table<receipt> receipt
		{
			get
			{
				return this.GetTable<receipt>();
			}
		}
		
		public System.Data.Linq.Table<config> config
		{
			get
			{
				return this.GetTable<config>();
			}
		}
		
		public System.Data.Linq.Table<genre> genre
		{
			get
			{
				return this.GetTable<genre>();
			}
		}
		
		public System.Data.Linq.Table<item> item
		{
			get
			{
				return this.GetTable<item>();
			}
		}
		
		public System.Data.Linq.Table<box> box
		{
			get
			{
				return this.GetTable<box>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.operator")]
	public partial class @operator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _operator_id;
		
		private string _operator_name;
		
		private string _operator_comment;
		
		private EntitySet<receipt> _receipt;
		
		private EntitySet<item> _item;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onoperator_idChanging(int value);
    partial void Onoperator_idChanged();
    partial void Onoperator_nameChanging(string value);
    partial void Onoperator_nameChanged();
    partial void Onoperator_commentChanging(string value);
    partial void Onoperator_commentChanged();
    #endregion
		
		public @operator()
		{
			this._receipt = new EntitySet<receipt>(new Action<receipt>(this.attach_receipt), new Action<receipt>(this.detach_receipt));
			this._item = new EntitySet<item>(new Action<item>(this.attach_item), new Action<item>(this.detach_item));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int operator_id
		{
			get
			{
				return this._operator_id;
			}
			set
			{
				if ((this._operator_id != value))
				{
					this.Onoperator_idChanging(value);
					this.SendPropertyChanging();
					this._operator_id = value;
					this.SendPropertyChanged("operator_id");
					this.Onoperator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string operator_name
		{
			get
			{
				return this._operator_name;
			}
			set
			{
				if ((this._operator_name != value))
				{
					this.Onoperator_nameChanging(value);
					this.SendPropertyChanging();
					this._operator_name = value;
					this.SendPropertyChanged("operator_name");
					this.Onoperator_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_comment", DbType="NVarChar(255)")]
		public string operator_comment
		{
			get
			{
				return this._operator_comment;
			}
			set
			{
				if ((this._operator_comment != value))
				{
					this.Onoperator_commentChanging(value);
					this.SendPropertyChanging();
					this._operator_comment = value;
					this.SendPropertyChanged("operator_comment");
					this.Onoperator_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="operator_receipt", Storage="_receipt", ThisKey="operator_id", OtherKey="receipt_operator")]
		public EntitySet<receipt> receipt
		{
			get
			{
				return this._receipt;
			}
			set
			{
				this._receipt.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="operator_item", Storage="_item", ThisKey="operator_id", OtherKey="item_sell_operator")]
		public EntitySet<item> item
		{
			get
			{
				return this._item;
			}
			set
			{
				this._item.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_receipt(receipt entity)
		{
			this.SendPropertyChanging();
			entity.@operator = this;
		}
		
		private void detach_receipt(receipt entity)
		{
			this.SendPropertyChanging();
			entity.@operator = null;
		}
		
		private void attach_item(item entity)
		{
			this.SendPropertyChanging();
			entity.@operator = this;
		}
		
		private void detach_item(item entity)
		{
			this.SendPropertyChanging();
			entity.@operator = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.receipt")]
	public partial class receipt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _receipt_id;
		
		private string _receipt_pass;
		
		private string _receipt_seller;
		
		private string _receipt_seller_exname;
		
		private System.Nullable<System.DateTime> _receipt_time;
		
		private System.Nullable<int> _receipt_operator;
		
		private System.Nullable<bool> _receipt_payback;
		
		private string _receipt_comment;
		
		private EntitySet<item> _item;
		
		private EntityRef<@operator> _operator;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreceipt_idChanging(int value);
    partial void Onreceipt_idChanged();
    partial void Onreceipt_passChanging(string value);
    partial void Onreceipt_passChanged();
    partial void Onreceipt_sellerChanging(string value);
    partial void Onreceipt_sellerChanged();
    partial void Onreceipt_seller_exnameChanging(string value);
    partial void Onreceipt_seller_exnameChanged();
    partial void Onreceipt_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreceipt_timeChanged();
    partial void Onreceipt_operatorChanging(System.Nullable<int> value);
    partial void Onreceipt_operatorChanged();
    partial void Onreceipt_paybackChanging(System.Nullable<bool> value);
    partial void Onreceipt_paybackChanged();
    partial void Onreceipt_commentChanging(string value);
    partial void Onreceipt_commentChanged();
    #endregion
		
		public receipt()
		{
			this._item = new EntitySet<item>(new Action<item>(this.attach_item), new Action<item>(this.detach_item));
			this._operator = default(EntityRef<@operator>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int receipt_id
		{
			get
			{
				return this._receipt_id;
			}
			set
			{
				if ((this._receipt_id != value))
				{
					this.Onreceipt_idChanging(value);
					this.SendPropertyChanging();
					this._receipt_id = value;
					this.SendPropertyChanged("receipt_id");
					this.Onreceipt_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_pass", DbType="Char(8)")]
		public string receipt_pass
		{
			get
			{
				return this._receipt_pass;
			}
			set
			{
				if ((this._receipt_pass != value))
				{
					this.Onreceipt_passChanging(value);
					this.SendPropertyChanging();
					this._receipt_pass = value;
					this.SendPropertyChanged("receipt_pass");
					this.Onreceipt_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_seller", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string receipt_seller
		{
			get
			{
				return this._receipt_seller;
			}
			set
			{
				if ((this._receipt_seller != value))
				{
					this.Onreceipt_sellerChanging(value);
					this.SendPropertyChanging();
					this._receipt_seller = value;
					this.SendPropertyChanged("receipt_seller");
					this.Onreceipt_sellerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_seller_exname", DbType="NVarChar(64)")]
		public string receipt_seller_exname
		{
			get
			{
				return this._receipt_seller_exname;
			}
			set
			{
				if ((this._receipt_seller_exname != value))
				{
					this.Onreceipt_seller_exnameChanging(value);
					this.SendPropertyChanging();
					this._receipt_seller_exname = value;
					this.SendPropertyChanged("receipt_seller_exname");
					this.Onreceipt_seller_exnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> receipt_time
		{
			get
			{
				return this._receipt_time;
			}
			set
			{
				if ((this._receipt_time != value))
				{
					this.Onreceipt_timeChanging(value);
					this.SendPropertyChanging();
					this._receipt_time = value;
					this.SendPropertyChanged("receipt_time");
					this.Onreceipt_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_operator", DbType="Int")]
		public System.Nullable<int> receipt_operator
		{
			get
			{
				return this._receipt_operator;
			}
			set
			{
				if ((this._receipt_operator != value))
				{
					if (this._operator.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onreceipt_operatorChanging(value);
					this.SendPropertyChanging();
					this._receipt_operator = value;
					this.SendPropertyChanged("receipt_operator");
					this.Onreceipt_operatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_payback", DbType="Bit")]
		public System.Nullable<bool> receipt_payback
		{
			get
			{
				return this._receipt_payback;
			}
			set
			{
				if ((this._receipt_payback != value))
				{
					this.Onreceipt_paybackChanging(value);
					this.SendPropertyChanging();
					this._receipt_payback = value;
					this.SendPropertyChanged("receipt_payback");
					this.Onreceipt_paybackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_comment", DbType="NVarChar(255)")]
		public string receipt_comment
		{
			get
			{
				return this._receipt_comment;
			}
			set
			{
				if ((this._receipt_comment != value))
				{
					this.Onreceipt_commentChanging(value);
					this.SendPropertyChanging();
					this._receipt_comment = value;
					this.SendPropertyChanged("receipt_comment");
					this.Onreceipt_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receipt_item", Storage="_item", ThisKey="receipt_id", OtherKey="item_receipt_id")]
		public EntitySet<item> item
		{
			get
			{
				return this._item;
			}
			set
			{
				this._item.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="operator_receipt", Storage="_operator", ThisKey="receipt_operator", OtherKey="operator_id", IsForeignKey=true, DeleteRule="SET NULL")]
		public @operator @operator
		{
			get
			{
				return this._operator.Entity;
			}
			set
			{
				@operator previousValue = this._operator.Entity;
				if (((previousValue != value) 
							|| (this._operator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._operator.Entity = null;
						previousValue.receipt.Remove(this);
					}
					this._operator.Entity = value;
					if ((value != null))
					{
						value.receipt.Add(this);
						this._receipt_operator = value.operator_id;
					}
					else
					{
						this._receipt_operator = default(Nullable<int>);
					}
					this.SendPropertyChanged("@operator");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_item(item entity)
		{
			this.SendPropertyChanging();
			entity.receipt = this;
		}
		
		private void detach_item(item entity)
		{
			this.SendPropertyChanging();
			entity.receipt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.config")]
	public partial class config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _config_name;
		
		private string _config_value;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onconfig_nameChanging(string value);
    partial void Onconfig_nameChanged();
    partial void Onconfig_valueChanging(string value);
    partial void Onconfig_valueChanged();
    #endregion
		
		public config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_config_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string config_name
		{
			get
			{
				return this._config_name;
			}
			set
			{
				if ((this._config_name != value))
				{
					this.Onconfig_nameChanging(value);
					this.SendPropertyChanging();
					this._config_name = value;
					this.SendPropertyChanged("config_name");
					this.Onconfig_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_config_value", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string config_value
		{
			get
			{
				return this._config_value;
			}
			set
			{
				if ((this._config_value != value))
				{
					this.Onconfig_valueChanging(value);
					this.SendPropertyChanging();
					this._config_value = value;
					this.SendPropertyChanged("config_value");
					this.Onconfig_valueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.genre")]
	public partial class genre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _genre_id;
		
		private string _genre_name;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongenre_idChanging(int value);
    partial void Ongenre_idChanged();
    partial void Ongenre_nameChanging(string value);
    partial void Ongenre_nameChanged();
    #endregion
		
		public genre()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int genre_id
		{
			get
			{
				return this._genre_id;
			}
			set
			{
				if ((this._genre_id != value))
				{
					this.Ongenre_idChanging(value);
					this.SendPropertyChanging();
					this._genre_id = value;
					this.SendPropertyChanged("genre_id");
					this.Ongenre_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string genre_name
		{
			get
			{
				return this._genre_name;
			}
			set
			{
				if ((this._genre_name != value))
				{
					this.Ongenre_nameChanging(value);
					this.SendPropertyChanging();
					this._genre_name = value;
					this.SendPropertyChanged("genre_name");
					this.Ongenre_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item")]
	public partial class item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private int _item_receipt_id;
		
		private string _item_name;
		
		private int _item_tagprice;
		
		private bool _item_tataki;
		
		private bool _item_return;
		
		private System.Nullable<int> _item_genre;
		
		private string _item_sellway;
		
		private System.Nullable<System.DateTime> _item_receipt_time;
		
		private System.Nullable<int> _item_receipt_operator;
		
		private System.Nullable<int> _item_sellprice;
		
		private System.Nullable<System.DateTime> _item_selltime;
		
		private System.Nullable<int> _item_sell_operator;
		
		private System.Nullable<System.DateTime> _item_kansa_end;
		
		private System.Nullable<int> _item_kansa_flag1;
		
		private System.Nullable<int> _item_adjust;
		
		private string _item_isbn;
		
		private System.Nullable<int> _item_volumes;
		
		private string _item_comment;
		
		private string _item_sellcomment;
		
		private string _item_userspace;
		
		private System.Nullable<int> _item_box_id;
		
		private System.Nullable<int> _item_number;
		
		private bool _item_tag_printed;
		
		private bool _item_supplement;
		
		private System.Nullable<int> _item_sellprice_bag;
		
		private EntityRef<receipt> _receipt;
		
		private EntityRef<@operator> _operator;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_receipt_idChanging(int value);
    partial void Onitem_receipt_idChanged();
    partial void Onitem_nameChanging(string value);
    partial void Onitem_nameChanged();
    partial void Onitem_tagpriceChanging(int value);
    partial void Onitem_tagpriceChanged();
    partial void Onitem_tatakiChanging(bool value);
    partial void Onitem_tatakiChanged();
    partial void Onitem_returnChanging(bool value);
    partial void Onitem_returnChanged();
    partial void Onitem_genreChanging(System.Nullable<int> value);
    partial void Onitem_genreChanged();
    partial void Onitem_sellwayChanging(string value);
    partial void Onitem_sellwayChanged();
    partial void Onitem_receipt_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onitem_receipt_timeChanged();
    partial void Onitem_receipt_operatorChanging(System.Nullable<int> value);
    partial void Onitem_receipt_operatorChanged();
    partial void Onitem_sellpriceChanging(System.Nullable<int> value);
    partial void Onitem_sellpriceChanged();
    partial void Onitem_selltimeChanging(System.Nullable<System.DateTime> value);
    partial void Onitem_selltimeChanged();
    partial void Onitem_sell_operatorChanging(System.Nullable<int> value);
    partial void Onitem_sell_operatorChanged();
    partial void Onitem_kansa_endChanging(System.Nullable<System.DateTime> value);
    partial void Onitem_kansa_endChanged();
    partial void Onitem_kansa_flag1Changing(System.Nullable<int> value);
    partial void Onitem_kansa_flag1Changed();
    partial void Onitem_adjustChanging(System.Nullable<int> value);
    partial void Onitem_adjustChanged();
    partial void Onitem_isbnChanging(string value);
    partial void Onitem_isbnChanged();
    partial void Onitem_volumesChanging(System.Nullable<int> value);
    partial void Onitem_volumesChanged();
    partial void Onitem_commentChanging(string value);
    partial void Onitem_commentChanged();
    partial void Onitem_sellcommentChanging(string value);
    partial void Onitem_sellcommentChanged();
    partial void Onitem_userspaceChanging(string value);
    partial void Onitem_userspaceChanged();
    partial void Onitem_box_idChanging(System.Nullable<int> value);
    partial void Onitem_box_idChanged();
    partial void Onitem_numberChanging(System.Nullable<int> value);
    partial void Onitem_numberChanged();
    partial void Onitem_tag_printedChanging(bool value);
    partial void Onitem_tag_printedChanged();
    partial void Onitem_supplementChanging(bool value);
    partial void Onitem_supplementChanged();
    partial void Onitem_sellprice_bagChanging(System.Nullable<int> value);
    partial void Onitem_sellprice_bagChanged();
    #endregion
		
		public item()
		{
			this._receipt = default(EntityRef<receipt>);
			this._operator = default(EntityRef<@operator>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_receipt_id", DbType="Int NOT NULL")]
		public int item_receipt_id
		{
			get
			{
				return this._item_receipt_id;
			}
			set
			{
				if ((this._item_receipt_id != value))
				{
					if (this._receipt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_receipt_idChanging(value);
					this.SendPropertyChanging();
					this._item_receipt_id = value;
					this.SendPropertyChanged("item_receipt_id");
					this.Onitem_receipt_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this.Onitem_nameChanging(value);
					this.SendPropertyChanging();
					this._item_name = value;
					this.SendPropertyChanged("item_name");
					this.Onitem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_tagprice", DbType="Int NOT NULL")]
		public int item_tagprice
		{
			get
			{
				return this._item_tagprice;
			}
			set
			{
				if ((this._item_tagprice != value))
				{
					this.Onitem_tagpriceChanging(value);
					this.SendPropertyChanging();
					this._item_tagprice = value;
					this.SendPropertyChanged("item_tagprice");
					this.Onitem_tagpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_tataki", DbType="Bit NOT NULL")]
		public bool item_tataki
		{
			get
			{
				return this._item_tataki;
			}
			set
			{
				if ((this._item_tataki != value))
				{
					this.Onitem_tatakiChanging(value);
					this.SendPropertyChanging();
					this._item_tataki = value;
					this.SendPropertyChanged("item_tataki");
					this.Onitem_tatakiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_return", DbType="Bit NOT NULL")]
		public bool item_return
		{
			get
			{
				return this._item_return;
			}
			set
			{
				if ((this._item_return != value))
				{
					this.Onitem_returnChanging(value);
					this.SendPropertyChanging();
					this._item_return = value;
					this.SendPropertyChanged("item_return");
					this.Onitem_returnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_genre", DbType="Int")]
		public System.Nullable<int> item_genre
		{
			get
			{
				return this._item_genre;
			}
			set
			{
				if ((this._item_genre != value))
				{
					this.Onitem_genreChanging(value);
					this.SendPropertyChanging();
					this._item_genre = value;
					this.SendPropertyChanged("item_genre");
					this.Onitem_genreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_sellway", DbType="NVarChar(255)")]
		public string item_sellway
		{
			get
			{
				return this._item_sellway;
			}
			set
			{
				if ((this._item_sellway != value))
				{
					this.Onitem_sellwayChanging(value);
					this.SendPropertyChanging();
					this._item_sellway = value;
					this.SendPropertyChanged("item_sellway");
					this.Onitem_sellwayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_receipt_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> item_receipt_time
		{
			get
			{
				return this._item_receipt_time;
			}
			set
			{
				if ((this._item_receipt_time != value))
				{
					this.Onitem_receipt_timeChanging(value);
					this.SendPropertyChanging();
					this._item_receipt_time = value;
					this.SendPropertyChanged("item_receipt_time");
					this.Onitem_receipt_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_receipt_operator", DbType="Int")]
		public System.Nullable<int> item_receipt_operator
		{
			get
			{
				return this._item_receipt_operator;
			}
			set
			{
				if ((this._item_receipt_operator != value))
				{
					this.Onitem_receipt_operatorChanging(value);
					this.SendPropertyChanging();
					this._item_receipt_operator = value;
					this.SendPropertyChanged("item_receipt_operator");
					this.Onitem_receipt_operatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_sellprice", DbType="Int")]
		public System.Nullable<int> item_sellprice
		{
			get
			{
				return this._item_sellprice;
			}
			set
			{
				if ((this._item_sellprice != value))
				{
					this.Onitem_sellpriceChanging(value);
					this.SendPropertyChanging();
					this._item_sellprice = value;
					this.SendPropertyChanged("item_sellprice");
					this.Onitem_sellpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_selltime", DbType="DateTime")]
		public System.Nullable<System.DateTime> item_selltime
		{
			get
			{
				return this._item_selltime;
			}
			set
			{
				if ((this._item_selltime != value))
				{
					this.Onitem_selltimeChanging(value);
					this.SendPropertyChanging();
					this._item_selltime = value;
					this.SendPropertyChanged("item_selltime");
					this.Onitem_selltimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_sell_operator", DbType="Int")]
		public System.Nullable<int> item_sell_operator
		{
			get
			{
				return this._item_sell_operator;
			}
			set
			{
				if ((this._item_sell_operator != value))
				{
					if (this._operator.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_sell_operatorChanging(value);
					this.SendPropertyChanging();
					this._item_sell_operator = value;
					this.SendPropertyChanged("item_sell_operator");
					this.Onitem_sell_operatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_kansa_end", DbType="DateTime")]
		public System.Nullable<System.DateTime> item_kansa_end
		{
			get
			{
				return this._item_kansa_end;
			}
			set
			{
				if ((this._item_kansa_end != value))
				{
					this.Onitem_kansa_endChanging(value);
					this.SendPropertyChanging();
					this._item_kansa_end = value;
					this.SendPropertyChanged("item_kansa_end");
					this.Onitem_kansa_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_kansa_flag1", DbType="Int")]
		public System.Nullable<int> item_kansa_flag1
		{
			get
			{
				return this._item_kansa_flag1;
			}
			set
			{
				if ((this._item_kansa_flag1 != value))
				{
					this.Onitem_kansa_flag1Changing(value);
					this.SendPropertyChanging();
					this._item_kansa_flag1 = value;
					this.SendPropertyChanged("item_kansa_flag1");
					this.Onitem_kansa_flag1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_adjust", DbType="Int")]
		public System.Nullable<int> item_adjust
		{
			get
			{
				return this._item_adjust;
			}
			set
			{
				if ((this._item_adjust != value))
				{
					this.Onitem_adjustChanging(value);
					this.SendPropertyChanging();
					this._item_adjust = value;
					this.SendPropertyChanged("item_adjust");
					this.Onitem_adjustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_isbn", DbType="NVarChar(255)")]
		public string item_isbn
		{
			get
			{
				return this._item_isbn;
			}
			set
			{
				if ((this._item_isbn != value))
				{
					this.Onitem_isbnChanging(value);
					this.SendPropertyChanging();
					this._item_isbn = value;
					this.SendPropertyChanged("item_isbn");
					this.Onitem_isbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_volumes", DbType="Int")]
		public System.Nullable<int> item_volumes
		{
			get
			{
				return this._item_volumes;
			}
			set
			{
				if ((this._item_volumes != value))
				{
					this.Onitem_volumesChanging(value);
					this.SendPropertyChanging();
					this._item_volumes = value;
					this.SendPropertyChanged("item_volumes");
					this.Onitem_volumesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_comment", DbType="NVarChar(255)")]
		public string item_comment
		{
			get
			{
				return this._item_comment;
			}
			set
			{
				if ((this._item_comment != value))
				{
					this.Onitem_commentChanging(value);
					this.SendPropertyChanging();
					this._item_comment = value;
					this.SendPropertyChanged("item_comment");
					this.Onitem_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_sellcomment", DbType="NVarChar(255)")]
		public string item_sellcomment
		{
			get
			{
				return this._item_sellcomment;
			}
			set
			{
				if ((this._item_sellcomment != value))
				{
					this.Onitem_sellcommentChanging(value);
					this.SendPropertyChanging();
					this._item_sellcomment = value;
					this.SendPropertyChanged("item_sellcomment");
					this.Onitem_sellcommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_userspace", DbType="NVarChar(255)")]
		public string item_userspace
		{
			get
			{
				return this._item_userspace;
			}
			set
			{
				if ((this._item_userspace != value))
				{
					this.Onitem_userspaceChanging(value);
					this.SendPropertyChanging();
					this._item_userspace = value;
					this.SendPropertyChanged("item_userspace");
					this.Onitem_userspaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_box_id", DbType="Int")]
		public System.Nullable<int> item_box_id
		{
			get
			{
				return this._item_box_id;
			}
			set
			{
				if ((this._item_box_id != value))
				{
					this.Onitem_box_idChanging(value);
					this.SendPropertyChanging();
					this._item_box_id = value;
					this.SendPropertyChanged("item_box_id");
					this.Onitem_box_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_number", DbType="Int")]
		public System.Nullable<int> item_number
		{
			get
			{
				return this._item_number;
			}
			set
			{
				if ((this._item_number != value))
				{
					this.Onitem_numberChanging(value);
					this.SendPropertyChanging();
					this._item_number = value;
					this.SendPropertyChanged("item_number");
					this.Onitem_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_tag_printed", DbType="Bit NOT NULL")]
		public bool item_tag_printed
		{
			get
			{
				return this._item_tag_printed;
			}
			set
			{
				if ((this._item_tag_printed != value))
				{
					this.Onitem_tag_printedChanging(value);
					this.SendPropertyChanging();
					this._item_tag_printed = value;
					this.SendPropertyChanged("item_tag_printed");
					this.Onitem_tag_printedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_supplement", DbType="Bit NOT NULL")]
		public bool item_supplement
		{
			get
			{
				return this._item_supplement;
			}
			set
			{
				if ((this._item_supplement != value))
				{
					this.Onitem_supplementChanging(value);
					this.SendPropertyChanging();
					this._item_supplement = value;
					this.SendPropertyChanged("item_supplement");
					this.Onitem_supplementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_sellprice_bag", DbType="Int")]
		public System.Nullable<int> item_sellprice_bag
		{
			get
			{
				return this._item_sellprice_bag;
			}
			set
			{
				if ((this._item_sellprice_bag != value))
				{
					this.Onitem_sellprice_bagChanging(value);
					this.SendPropertyChanging();
					this._item_sellprice_bag = value;
					this.SendPropertyChanged("item_sellprice_bag");
					this.Onitem_sellprice_bagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receipt_item", Storage="_receipt", ThisKey="item_receipt_id", OtherKey="receipt_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public receipt receipt
		{
			get
			{
				return this._receipt.Entity;
			}
			set
			{
				receipt previousValue = this._receipt.Entity;
				if (((previousValue != value) 
							|| (this._receipt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._receipt.Entity = null;
						previousValue.item.Remove(this);
					}
					this._receipt.Entity = value;
					if ((value != null))
					{
						value.item.Add(this);
						this._item_receipt_id = value.receipt_id;
					}
					else
					{
						this._item_receipt_id = default(int);
					}
					this.SendPropertyChanged("receipt");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="operator_item", Storage="_operator", ThisKey="item_sell_operator", OtherKey="operator_id", IsForeignKey=true, DeleteRule="SET NULL")]
		public @operator @operator
		{
			get
			{
				return this._operator.Entity;
			}
			set
			{
				@operator previousValue = this._operator.Entity;
				if (((previousValue != value) 
							|| (this._operator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._operator.Entity = null;
						previousValue.item.Remove(this);
					}
					this._operator.Entity = value;
					if ((value != null))
					{
						value.item.Add(this);
						this._item_sell_operator = value.operator_id;
					}
					else
					{
						this._item_sell_operator = default(Nullable<int>);
					}
					this.SendPropertyChanged("@operator");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.box")]
	public partial class box : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _box_id;
		
		private int _box_genre;
		
		private string _box_comment;
		
		private bool _box_isbag;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbox_idChanging(int value);
    partial void Onbox_idChanged();
    partial void Onbox_genreChanging(int value);
    partial void Onbox_genreChanged();
    partial void Onbox_commentChanging(string value);
    partial void Onbox_commentChanged();
    partial void Onbox_isbagChanging(bool value);
    partial void Onbox_isbagChanged();
    #endregion
		
		public box()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_box_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int box_id
		{
			get
			{
				return this._box_id;
			}
			set
			{
				if ((this._box_id != value))
				{
					this.Onbox_idChanging(value);
					this.SendPropertyChanging();
					this._box_id = value;
					this.SendPropertyChanged("box_id");
					this.Onbox_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_box_genre", DbType="Int NOT NULL")]
		public int box_genre
		{
			get
			{
				return this._box_genre;
			}
			set
			{
				if ((this._box_genre != value))
				{
					this.Onbox_genreChanging(value);
					this.SendPropertyChanging();
					this._box_genre = value;
					this.SendPropertyChanged("box_genre");
					this.Onbox_genreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_box_comment", DbType="NVarChar(255)")]
		public string box_comment
		{
			get
			{
				return this._box_comment;
			}
			set
			{
				if ((this._box_comment != value))
				{
					this.Onbox_commentChanging(value);
					this.SendPropertyChanging();
					this._box_comment = value;
					this.SendPropertyChanged("box_comment");
					this.Onbox_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_box_isbag", DbType="Bit NOT NULL")]
		public bool box_isbag
		{
			get
			{
				return this._box_isbag;
			}
			set
			{
				if ((this._box_isbag != value))
				{
					this.Onbox_isbagChanging(value);
					this.SendPropertyChanging();
					this._box_isbag = value;
					this.SendPropertyChanged("box_isbag");
					this.Onbox_isbagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
