#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kaede3rd
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="itemregister")]
	public partial class WebRegisterItemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void Insertwritem(writem instance);
    partial void Updatewritem(writem instance);
    partial void Deletewritem(writem instance);
    partial void Insertwrreceipt(wrreceipt instance);
    partial void Updatewrreceipt(wrreceipt instance);
    partial void Deletewrreceipt(wrreceipt instance);
    #endregion
		
		public WebRegisterItemDataContext() : 
				base(global::huruhon.Properties.Settings.Default.itemregisterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebRegisterItemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebRegisterItemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebRegisterItemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebRegisterItemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<writem> writem
		{
			get
			{
				return this.GetTable<writem>();
			}
		}
		
		public System.Data.Linq.Table<wrreceipt> wrreceipt
		{
			get
			{
				return this.GetTable<wrreceipt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item")]
	public partial class writem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _item_id;
		
		private int _item_receipt_id;
		
		private string _item_name;
		
		private int _item_tagprice;
		
		private bool _item_return;
		
		private System.Nullable<System.DateTime> _item_receipt_time;
		
		private System.Nullable<int> _item_number;
		
		private string _item_comment;
		
		private EntityRef<wrreceipt> _wrreceipt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onitem_idChanging(int value);
    partial void Onitem_idChanged();
    partial void Onitem_receipt_idChanging(int value);
    partial void Onitem_receipt_idChanged();
    partial void Onitem_nameChanging(string value);
    partial void Onitem_nameChanged();
    partial void Onitem_tagpriceChanging(int value);
    partial void Onitem_tagpriceChanged();
    partial void Onitem_returnChanging(bool value);
    partial void Onitem_returnChanged();
    partial void Onitem_receipt_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onitem_receipt_timeChanged();
    partial void Onitem_numberChanging(System.Nullable<int> value);
    partial void Onitem_numberChanged();
    partial void Onitem_commentChanging(string value);
    partial void Onitem_commentChanged();
    #endregion
		
		public writem()
		{
			this._wrreceipt = default(EntityRef<wrreceipt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_receipt_id", DbType="Int NOT NULL")]
		public int item_receipt_id
		{
			get
			{
				return this._item_receipt_id;
			}
			set
			{
				if ((this._item_receipt_id != value))
				{
					if (this._wrreceipt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onitem_receipt_idChanging(value);
					this.SendPropertyChanging();
					this._item_receipt_id = value;
					this.SendPropertyChanged("item_receipt_id");
					this.Onitem_receipt_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this.Onitem_nameChanging(value);
					this.SendPropertyChanging();
					this._item_name = value;
					this.SendPropertyChanged("item_name");
					this.Onitem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_tagprice", DbType="Int NOT NULL")]
		public int item_tagprice
		{
			get
			{
				return this._item_tagprice;
			}
			set
			{
				if ((this._item_tagprice != value))
				{
					this.Onitem_tagpriceChanging(value);
					this.SendPropertyChanging();
					this._item_tagprice = value;
					this.SendPropertyChanged("item_tagprice");
					this.Onitem_tagpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_return", DbType="Bit NOT NULL")]
		public bool item_return
		{
			get
			{
				return this._item_return;
			}
			set
			{
				if ((this._item_return != value))
				{
					this.Onitem_returnChanging(value);
					this.SendPropertyChanging();
					this._item_return = value;
					this.SendPropertyChanged("item_return");
					this.Onitem_returnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_receipt_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> item_receipt_time
		{
			get
			{
				return this._item_receipt_time;
			}
			set
			{
				if ((this._item_receipt_time != value))
				{
					this.Onitem_receipt_timeChanging(value);
					this.SendPropertyChanging();
					this._item_receipt_time = value;
					this.SendPropertyChanged("item_receipt_time");
					this.Onitem_receipt_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_number", DbType="Int")]
		public System.Nullable<int> item_number
		{
			get
			{
				return this._item_number;
			}
			set
			{
				if ((this._item_number != value))
				{
					this.Onitem_numberChanging(value);
					this.SendPropertyChanging();
					this._item_number = value;
					this.SendPropertyChanged("item_number");
					this.Onitem_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_comment", DbType="NVarChar(255)")]
		public string item_comment
		{
			get
			{
				return this._item_comment;
			}
			set
			{
				if ((this._item_comment != value))
				{
					this.Onitem_commentChanging(value);
					this.SendPropertyChanging();
					this._item_comment = value;
					this.SendPropertyChanged("item_comment");
					this.Onitem_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receipt_writem", Storage="_wrreceipt", ThisKey="item_receipt_id", OtherKey="receipt_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public wrreceipt wrreceipt
		{
			get
			{
				return this._wrreceipt.Entity;
			}
			set
			{
				wrreceipt previousValue = this._wrreceipt.Entity;
				if (((previousValue != value) 
							|| (this._wrreceipt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._wrreceipt.Entity = null;
						previousValue.writem.Remove(this);
					}
					this._wrreceipt.Entity = value;
					if ((value != null))
					{
						value.writem.Add(this);
						this._item_receipt_id = value.receipt_id;
					}
					else
					{
						this._item_receipt_id = default(int);
					}
					this.SendPropertyChanged("wrreceipt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.receipt")]
	public partial class wrreceipt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _receipt_id;
		
		private System.Guid _receipt_userid;
		
		private string _receipt_seller;
		
		private string _receipt_seller_exname;
		
		private System.Nullable<System.DateTime> _receipt_time;
		
		private string _receipt_comment;
		
		private bool _receipt_registerd;
		
		private int _receipt_bumon;
		
		private string _receipt_email;
		
		private EntitySet<writem> _writem;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreceipt_idChanging(int value);
    partial void Onreceipt_idChanged();
    partial void Onreceipt_useridChanging(System.Guid value);
    partial void Onreceipt_useridChanged();
    partial void Onreceipt_sellerChanging(string value);
    partial void Onreceipt_sellerChanged();
    partial void Onreceipt_seller_exnameChanging(string value);
    partial void Onreceipt_seller_exnameChanged();
    partial void Onreceipt_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreceipt_timeChanged();
    partial void Onreceipt_commentChanging(string value);
    partial void Onreceipt_commentChanged();
    partial void Onreceipt_registerdChanging(bool value);
    partial void Onreceipt_registerdChanged();
    partial void Onreceipt_bumonChanging(int value);
    partial void Onreceipt_bumonChanged();
    partial void Onreceipt_emailChanging(string value);
    partial void Onreceipt_emailChanged();
    #endregion
		
		public wrreceipt()
		{
			this._writem = new EntitySet<writem>(new Action<writem>(this.attach_writem), new Action<writem>(this.detach_writem));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int receipt_id
		{
			get
			{
				return this._receipt_id;
			}
			set
			{
				if ((this._receipt_id != value))
				{
					this.Onreceipt_idChanging(value);
					this.SendPropertyChanging();
					this._receipt_id = value;
					this.SendPropertyChanged("receipt_id");
					this.Onreceipt_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_userid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid receipt_userid
		{
			get
			{
				return this._receipt_userid;
			}
			set
			{
				if ((this._receipt_userid != value))
				{
					this.Onreceipt_useridChanging(value);
					this.SendPropertyChanging();
					this._receipt_userid = value;
					this.SendPropertyChanged("receipt_userid");
					this.Onreceipt_useridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_seller", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string receipt_seller
		{
			get
			{
				return this._receipt_seller;
			}
			set
			{
				if ((this._receipt_seller != value))
				{
					this.Onreceipt_sellerChanging(value);
					this.SendPropertyChanging();
					this._receipt_seller = value;
					this.SendPropertyChanged("receipt_seller");
					this.Onreceipt_sellerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_seller_exname", DbType="NVarChar(64)")]
		public string receipt_seller_exname
		{
			get
			{
				return this._receipt_seller_exname;
			}
			set
			{
				if ((this._receipt_seller_exname != value))
				{
					this.Onreceipt_seller_exnameChanging(value);
					this.SendPropertyChanging();
					this._receipt_seller_exname = value;
					this.SendPropertyChanged("receipt_seller_exname");
					this.Onreceipt_seller_exnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> receipt_time
		{
			get
			{
				return this._receipt_time;
			}
			set
			{
				if ((this._receipt_time != value))
				{
					this.Onreceipt_timeChanging(value);
					this.SendPropertyChanging();
					this._receipt_time = value;
					this.SendPropertyChanged("receipt_time");
					this.Onreceipt_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_comment", DbType="NVarChar(255)")]
		public string receipt_comment
		{
			get
			{
				return this._receipt_comment;
			}
			set
			{
				if ((this._receipt_comment != value))
				{
					this.Onreceipt_commentChanging(value);
					this.SendPropertyChanging();
					this._receipt_comment = value;
					this.SendPropertyChanged("receipt_comment");
					this.Onreceipt_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_registerd", DbType="Bit NOT NULL")]
		public bool receipt_registerd
		{
			get
			{
				return this._receipt_registerd;
			}
			set
			{
				if ((this._receipt_registerd != value))
				{
					this.Onreceipt_registerdChanging(value);
					this.SendPropertyChanging();
					this._receipt_registerd = value;
					this.SendPropertyChanged("receipt_registerd");
					this.Onreceipt_registerdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_bumon", DbType="Int NOT NULL")]
		public int receipt_bumon
		{
			get
			{
				return this._receipt_bumon;
			}
			set
			{
				if ((this._receipt_bumon != value))
				{
					this.Onreceipt_bumonChanging(value);
					this.SendPropertyChanging();
					this._receipt_bumon = value;
					this.SendPropertyChanged("receipt_bumon");
					this.Onreceipt_bumonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receipt_email", DbType="NVarChar(64)")]
		public string receipt_email
		{
			get
			{
				return this._receipt_email;
			}
			set
			{
				if ((this._receipt_email != value))
				{
					this.Onreceipt_emailChanging(value);
					this.SendPropertyChanging();
					this._receipt_email = value;
					this.SendPropertyChanged("receipt_email");
					this.Onreceipt_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receipt_writem", Storage="_writem", ThisKey="receipt_id", OtherKey="item_receipt_id")]
		public EntitySet<writem> writem
		{
			get
			{
				return this._writem;
			}
			set
			{
				this._writem.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_writem(writem entity)
		{
			this.SendPropertyChanging();
			entity.wrreceipt = this;
		}
		
		private void detach_writem(writem entity)
		{
			this.SendPropertyChanging();
			entity.wrreceipt = null;
		}
	}
}
#pragma warning restore 1591
